### ISSUE TITLE
IntelliJ and SBT will re-compile each other's classes, even if nothing changes

### ISSUE THREAD

**Issue by RichardBradley** [JetBrains/intellij-scala#131]
I use both SBT and IntelliJ 14.
I have found that they do not seem to like each other's classes, in the sense that SBT will do a full recompile if IntelliJ last built the project and vice-versa, even when nothing has changed.

Is there any way to configure things so that this doesn't happen? It's very time-consuming.

I have:
 * Windows 7
 * Java 64-Bit "1.6.0_21"
 * SBT is configured to use Scala 2.11.5 and Java 1.6
 * IntelliJ 14.0.3
 * IntelliJ Scala plugin 1.3.3
 * My project is configured from SBT in IntelliJ

Thanks,

Rich

**Comment by niktrop** [comment]
Hi, Richard,
Incremental compilers of SBT and IDEA does not know about each other. And currently there is no way to reuse results of one from another. So to have incremental compilation you need to use different output directories for them. You can change output paths for IDEA in the Project Settings or edit .iml files in the .idea/modules directory.

Currently there is a problem with this workaround, because on the refresh of sbt project output paths will synchronize back. I created an issue in our bugtracker:
https://youtrack.jetbrains.com/issue/SCL-8481

**Comment by RichardBradley** [comment]
Thanks, that makes sense.

> currently there is no way to reuse results of one from another

Out of interest, do you know the details of why that is?

How do each of IntelliJ and SBT use to decide whether to recompile a class or not? In my mental model they would just use something like file timestamps, but clearly they are doing something else.

**Comment by niktrop** [comment]
Incremental compiler should compile all changed sources and iteratively find and recompile all files depending from them. So it need to know which files were changed from the last compilation and have some kind of dependency graph, which should be updated during the compilation. This information is very implementation specific and requires some level of control on the sources and classfiles.

Intellij IDEA has two built-in incremental compilers for scala. First is based on scalac and our java incremental compiler, second uses a little modified incremental compiler from sbt. Probably it is possible to sync the second one with a standalone instance of sbt process, but it has a small chance to be done. We are going to support sbt server soon, which will be possible to use both from the console and to perform different tasks for IDE.

**Comment by RichardBradley** [comment]
I see, thanks. 

Having the IDEA SBT plugin put the SBT and IDEA classes in separate directories seems like the best fix, I agree.
