### ISSUE TITLE
Simplification suggestion with incompatible types

### ISSUE THREAD

**Issue by felixbr** [JetBrains/intellij-scala#136]
When writing something like

    val a = Seq("super", "nova")
    a.reduce(_ + _)

Intellij issues a warning on the second line and wants it to be simplified to `a.sum`. The latter doesn't work because there is no implicit value for its parameter `num: Numeric[String]`.

I understand this is a tricky issue, but I think it's important because this may trip up newcomers to the language. It's not particularly fun to suppress statements because you know the IDE is wrong either.

**Comment by niktrop** [comment]
Hi Felix,
Actually we do check presence of the implicit parameter in that inspection. 
![2015-03-23 10-01-32](https://cloud.githubusercontent.com/assets/3604749/6775553/d3a533e4-d143-11e4-9798-16341f02e009.png)

What version of the plugin do you use? Maybe you have such implicit parameter somewhere in your project? Since version 1.4 we have an improved tool to analyze implicit parameters (Ctrl+Shift+P): 
http://blog.jetbrains.com/scala/2015/03/05/scala-1-4-eap-brings-advanced-implicits-analyzer-and-faster-play-compiler/

**Comment by felixbr** [comment]
Well, for some reason it doesn't work the same way on my end: ![Image of IntelliJ](http://puu.sh/gNIk9/98115d3681.png)

I'm using the 1.4 Plugin (release channel) with IntelliJ Ultimate 14.0.3.

If I can provide you with anything else to debug this problem, just let me know.

**Comment by niktrop** [comment]
You are right, there is a bug in that version of the plugin. It is fixed in master already. Thanks for reporting!
