### ISSUE TITLE
Importing large projects takes a long time

### ISSUE THREAD

**Issue by cowboygneox** [JetBrains/intellij-scala#192]
We've been trying to consolidate our related projects into one repository. Unfortunately for us, even though we were trying to avoid the monolithic service, that's essentially what we have, and we're bringing it together so that we can consolidate and potentially split in the future.

That being said, a 54 project multi-project in SBT is currently taking my top-of-the-line MacBook Pro 15" 6 minutes to do the initial import, followed by another 6 minutes after IntelliJ loads. Once IntelliJ loads, life is good and it works great with that many projects, but getting there is unbearable.

I will gladly help improve the speed if someone could point me in the right direction. It seems unreasonable that SBT can compile all of the sources in the time it takes for IntelliJ to load them. 

Any thoughts?

**Comment by nkly** [comment]
Hi! Thanks for the report. This is known issue: https://youtrack.jetbrains.com/issue/SCL-8322. We're working on it, but, unfortunately, have not come up with a solution yet. You may achieve some boost using cached resolution introduced in SBT 0.13.7, but I can't guarantee that.

The problem is reproduced in highly dependent or aggregated projects. In order to get full information about library dependencies, we run `update` task on every project in a build. Suppose you have three projects in a build: A, B and C. A aggregates B and B depends on C. We run `update` on each of these project, but for project C `update` will be executed 3 times. It happens for the first time when we read its own settings. Next, when we read B's settings we execute `update` on B, but because it depends on C `update` gets executed on it too. And finally, when we read A's settings we execute `update` on A, but because it aggregates B, SBT executes `update` on B and, therefore, on C too.
