### ISSUE TITLE
'No main class detected' for standard Play 2 run configuration

### ISSUE THREAD

**Issue by DavidNiehues** [JetBrains/intellij-scala#200]
Hi,

in our project we currently have the problem, that we can't run/debug our play application from IntelliJ IDEA with the latest version (1.5.2) of the scala plugin. Always the the exception

```
java.lang.RuntimeException: No main class detected.
    at scala.sys.package$.error(package.scala:27)
```

occurs.
Our Build.scala defines

``` scala
val main = play.Project(appName, appVersion, appDependencies)
    .settings(resolvers += Resolver.sonatypeRepo("releases"))
```

and in plugins.sbt we have

``` scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.6")
```

With the old versions of the plugin everyhting worked quite fine. But the latest version broke the support.
If you need more information to fix the problem, feel free to ask.

If someone else has the same problem, [this answer on Stackoverflow](http://stackoverflow.com/a/24542709/1937231) provided a workaround for us, but it reverted the IntelliJ Project format back, but it worked.

**Comment by Lugzan** [comment]
Hello, 
there was an issue related to wrong working dir after, but it should be fixed in the latest release. Also you can set working dir for the project in settings ("Project uri"): http://puu.sh/kJSU6/dd4073e0ca.png
If you encounter the same issue in the latest update, please use our bugtracker https://youtrack.jetbrains.com/issues to report it .
