### ISSUE TITLE
Plugin does not properly read all proxy settings and fail to resolve dependencies

### ISSUE THREAD

**Issue by monzonj** [JetBrains/intellij-scala#225]
This plugin ignores the setting `http.nonProxyHosts` and fails to resolve dependencies in networks where there's a proxy but also repositories that are not accessible through that proxy (like a nexus inside the network)

A solution is to add the setting in the .idea/play2_compiler_settings.xml :

```
  <component name="Play2CompilerConfiguration">
     ........
    <option name="SBT_OPTIONS" value="-Dhttp.nonProxyHosts=nexus" />
  </component>
```

But ideally this plugin should read the project SBT proxy configuration properly without having to manually deal with this.

**Comment by nkly** [comment]
Thanks for taking the time to report a problem. `http.nonProxyHosts` is VM option, not SBT's one, which means that you should set it manually in IDEA proxy settings so that it could be used. The current problem is that these settings are not used when SBT project is imported or Play2 project is compiled. I've created corresponding issues on our issue tracker: [regarding SBT](https://youtrack.jetbrains.com/issue/SCL-9288) and [regarding Play2](https://youtrack.jetbrains.com/issue/SCL-9289)
